
spring:
   datasource: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/chandra_db
      username: root
      password: root
   
logging:
  level:
    com.revature.course:
                       ERROR
  file: 
     name: app.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
     
     
     