package com.revature.course.junitTests.util;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import com.revature.course.dto.CategoryDTO;
import com.revature.course.dto.CourseDTO;
import com.revature.course.dto.LevelDTO;
import com.revature.course.dto.ReferenceArtifactsDTO;
import com.revature.course.dto.ReferenceUrlDTO;
import com.revature.course.dto.UsersDTO;

public class CourseDTOUtil {
	public static CourseDTO getCourseDTODetails() {
		CourseDTO course = new CourseDTO();
		course.setId(1);
		course.setName("java");
		LevelDTO level = new LevelDTO();
		level.setId(1);
		CategoryDTO categoryDTO = new CategoryDTO();
		categoryDTO.setId(1);
		course.setCategory(categoryDTO);
		course.setLevel(level);
		course.setCompletionPoint(100);
		UsersDTO usersDTO = new UsersDTO();
		usersDTO.setId(1);
		usersDTO.setEmail("chandra@gmail.com");
		usersDTO.setName("chandra");
		course.setCreatedBy(usersDTO);
		course.setDescription("it is description");
		course.setEnrollmentPoint(100);
		course.setLevelOverRide(true);
		course.setLoggedInViaSlug(true);
		course.setPreSignUp(true);
		course.setMetaDescription("it is meta description");
		course.setMetaKeyword("it is meta keyword");
		course.setSlug("www.app.revature.com/courses/java");
		course.setStatus(true);
		course.setTags("java,java programming");
		List<ReferenceArtifactsDTO> referenceArtifactsDTOList = new ArrayList<>();
		ReferenceArtifactsDTO referenceArtifactsDTO = new ReferenceArtifactsDTO();
		referenceArtifactsDTO.setId(1);
		referenceArtifactsDTO.setCourseId(1);
		referenceArtifactsDTO.setDescription("description for interfaces");
		referenceArtifactsDTO.setName("interfaces");
		referenceArtifactsDTO.setType("Main content");
		referenceArtifactsDTO.setFileName("interfaces.zip");
		referenceArtifactsDTOList.add(referenceArtifactsDTO);
		course.setReferenceArtifacts(referenceArtifactsDTOList);
		referenceArtifactsDTO = new ReferenceArtifactsDTO();
		referenceArtifactsDTO.setId(2);
		referenceArtifactsDTO.setCourseId(1);
		referenceArtifactsDTO.setDescription("description for polymorphism");
		referenceArtifactsDTO.setName("polymorphism");
		referenceArtifactsDTO.setFileName("polymorphism.zip");
		referenceArtifactsDTO.setType("Main content");
		referenceArtifactsDTOList.add(referenceArtifactsDTO);
		course.setReferenceArtifacts(referenceArtifactsDTOList);
		List<ReferenceUrlDTO> ReferenceUrlDTOList = new ArrayList<>();
		ReferenceUrlDTO referenceUrlDTO = new ReferenceUrlDTO();
		referenceUrlDTO.setId(1);
		referenceUrlDTO.setCourseId(1);
		referenceUrlDTO.setDescription("description for interfaces");
		referenceUrlDTO.setName("interfaces");
		referenceUrlDTO.setType("Main content");
		referenceUrlDTO.setTutorial(false);
		referenceUrlDTO.setUrl("www.revature.com/interfaces");
		ReferenceUrlDTOList.add(referenceUrlDTO);
		course.setRefernceUrl(ReferenceUrlDTOList);
		referenceUrlDTO = new ReferenceUrlDTO();
		referenceUrlDTO.setId(2);
		referenceUrlDTO.setCourseId(1);
		referenceUrlDTO.setDescription("description for polymorphism");
		referenceUrlDTO.setName("polymorphism");
		referenceUrlDTO.setType("Main content");
		referenceUrlDTO.setTutorial(true);
		referenceUrlDTO.setUrl("www.revature.com/polymorphism");
		ReferenceUrlDTOList.add(referenceUrlDTO);
		course.setRefernceUrl(ReferenceUrlDTOList);
		course.setIconName("rev-logo-2.png");
		File file=new File("C:/Users/Revature1/Downloads/rev-logo-2.png");
		course.setIcon(file);
		return course;
	}
}
